import type { Project } from '@/domain/project/Project';

export const PROJECTS_DATA: Project[] = [

  // FULLSTACK
  {
    id: 'arkabia-platform',
    title: 'Arkabia — Comercio Exterior SaaS',
    description: 'Plataforma SaaS peruana para importadores, exportadores y agentes de aduana. Gestión documental, trámites y flujos en tiempo real.',
    longDescription: 'Arkabia es una startup peruana de comercio exterior donde trabajo actualmente como Frontend Developer. Construí y mantuve múltiples módulos con React + TypeScript con arquitectura DDD.',
    category: 'fullstack',
    status: 'production',
    techs: [
      { name: 'React', color: 'cyan' },
      { name: 'TypeScript', color: 'blue' },
      { name: 'Tailwind CSS', color: 'teal' },
      { name: 'REST APIs', color: 'violet' },
    ],
    imagePlaceholder: 'AB',
    imageUrl: '/projects/arkabia.png',
    liveUrl: 'https://arkabia.com',
    featured: true,
    year: 2024,
    highlights: [
      'Plataforma en producción con usuarios reales',
      'Arquitectura de componentes escalable con DDD',
      'Integración con múltiples APIs de comercio exterior',
      'CI/CD con GitLab en equipo ágil',
    ],
  },
  {
    id: 'darkfunnels-fullstack',
    title: 'DarkFunnels.ai — Plataforma Fullstack IA',
    description: 'Plataforma fullstack de automatización de marketing en WhatsApp con IA. Frontend Angular + backend N8N. Voz, videos personalizados y flujos inteligentes en producción.',
    longDescription: 'DarkFunnels.ai es una plataforma en producción desarrollada como idea de negocio en el ecosistema de Arkabia. Frontend Angular completo y backend construido con N8N. Incluye integración de voz IA, videos personalizados por cliente y flujos complejos de conversación.',
    category: 'fullstack',
    status: 'production',
    techs: [
      { name: 'Angular', color: 'orange' },
      { name: 'TypeScript', color: 'blue' },
      { name: 'N8N', color: 'orange' },
      { name: 'AI/LLMs', color: 'violet' },
      { name: 'WhatsApp API', color: 'green' },
    ],
    imagePlaceholder: 'DF',
    imageUrl: '/projects/DarkFunnels.png',
    liveUrl: 'https://darkfunnels.ai',
    featured: true,
    year: 2024,
    highlights: [
      'Frontend Angular completo en producción',
      'Backend construido íntegramente con N8N',
      'Voz IA para mensajes de audio automáticos',
      'Videos personalizados generados con IA por lead',
      'Integración WhatsApp Business API',
    ],
  },
  {
    id: 'meproind-fullstack',
    title: 'Meproind — Plataforma Industrial IoT',
    description: 'Plataforma industrial para empresa minera: monitoreo y cálculo de costos de mesas gravimétricas, consumo eléctrico y de agua. Frontend React multilenguaje (i18n) + backend N8N. En producción.',
    longDescription: 'Meproind es una empresa de servicios mineros con plataforma propia, idea de negocio del ecosistema de Arkabia y hoy en producción. Frontend React multilenguaje (i18n: español, inglés y portugués) y backend íntegro en N8N, con un componente IoT/industrial para el monitoreo de mesas gravimétricas, consumo eléctrico y de agua.',
    category: 'iot',
    status: 'production',
    techs: [
      { name: 'React', color: 'cyan' },
      { name: 'TypeScript', color: 'blue' },
      { name: 'N8N', color: 'orange' },
      { name: 'REST APIs', color: 'violet' },
      { name: 'SQL', color: 'teal' },
      { name: 'IoT', color: 'orange' },
    ],
    imagePlaceholder: 'MP',
    imageUrl: '/projects/meproind.png',
    liveUrl: 'https://app.meproind.com',
    featured: true,
    year: 2025,
    highlights: [
      'Frontend React en producción',
      'Backend 100% N8N — sin servidor tradicional',
      'Cálculo de costos de mesas gravimétricas',
      'Estimados de consumo eléctrico y agua',
      'Precios diferenciados por tipo de mineral',
    ],
  },
  {
    id: 'car2go',
    title: 'Car2Go — Marketplace de Autos Certificados',
    description: 'Marketplace de autos de segunda mano con revisión y certificación por mecánicos. Microservicios Java Spring + frontend Angular, pagos con Stripe y ranking de vendedores y mecánicos.',
    longDescription: 'Proyecto académico con arquitectura de microservicios (Spring Cloud, service discovery con Eureka). Compra-venta de autos usados con flujo de revisión y certificación por mecánicos desde su propio panel, pasarela de pago Stripe, ranking de mejores vendedores y mecánicos, pruebas unitarias con JUnit y pipeline CI/CD.',
    category: 'fullstack',
    status: 'academic',
    techs: [
      { name: 'Java', color: 'orange' },
      { name: 'Spring Cloud', color: 'green' },
      { name: 'Microservicios', color: 'violet' },
      { name: 'Angular', color: 'orange' },
      { name: 'Stripe', color: 'cyan' },
      { name: 'JUnit', color: 'teal' },
      { name: 'CI/CD', color: 'blue' },
    ],
    imagePlaceholder: 'C2G',
    imageUrl: '/projects/Car2Go.png',
    githubUrl: 'https://github.com/LuisDiazpe/car2go-backend',
    featured: true,
    year: 2026,
    highlights: [
      'Microservicios con Spring Cloud y service discovery (Eureka)',
      'Certificación de vehículos por mecánicos con panel propio',
      'Pagos con Stripe y ranking de vendedores y mecánicos',
      'Pruebas unitarias con JUnit y pipeline CI/CD',
    ],
  },
  {
    id: 'skillshare',
    title: 'SkillShare — Grupos de Estudio',
    description: 'App móvil Flutter para crear grupos de estudio: ideas, debates y materiales compartidos, con notificaciones. Backend monolítico en C# .NET con APIs RESTful.',
    longDescription: 'Proyecto académico para conectar estudiantes en grupos de estudio con recomendaciones, debates y materiales compartidos. App Flutter con notificaciones, backend monolítico en C# .NET con APIs RESTful, pruebas unitarias con xUnit y NUnit, y pipeline CI/CD.',
    category: 'mobile',
    status: 'academic',
    techs: [
      { name: 'Flutter', color: 'cyan' },
      { name: 'Dart', color: 'blue' },
      { name: 'C# .NET', color: 'violet' },
      { name: 'REST APIs', color: 'teal' },
      { name: 'xUnit · NUnit', color: 'orange' },
      { name: 'CI/CD', color: 'green' },
    ],
    imagePlaceholder: 'SS',
    imageUrl: '/projects/SkillShare.png',
    githubUrl: 'https://github.com/Diseno-de-Experimentos-Skillshare/flutter-mobile-application',
    featured: true,
    year: 2026,
    highlights: [
      'Grupos de estudio con recomendaciones, debates y materiales',
      'Notificaciones integradas en la app móvil Flutter',
      'Backend monolítico C# .NET con APIs RESTful',
      'Pruebas unitarias con xUnit y NUnit + pipeline CI/CD',
    ],
  },
  {
    id: 'spliteasy-fullstack',
    title: 'SplitEasy — Gastos Compartidos',
    description: 'App para gestión de gastos entre grupos. Backend principal en Java Spring Boot con arquitectura DDD. Frontend Angular de integración.',
    longDescription: 'Proyecto académico con foco en backend. Domain Driven Design completo en Spring Boot, API RESTful con JWT. Frontend Angular como capa de integración.',
    category: 'fullstack',
    status: 'academic',
    techs: [
      { name: 'Java', color: 'orange' },
      { name: 'Spring Boot', color: 'green' },
      { name: 'DDD', color: 'violet' },
      { name: 'Angular', color: 'orange' },
      { name: 'MySQL', color: 'blue' },
    ],
    imagePlaceholder: 'SE',
    imageUrl: '/projects/SplitEasy.png',
    githubUrl: 'https://github.com/1ASI0729-2510-4313-G3-SplitEasy/backend-app',
    featured: false,
    year: 2024,
    highlights: [
      'Arquitectura DDD completa en backend Java',
      'API RESTful con Spring Boot y JWT',
      'Frontend Angular como capa de consumo',
    ],
  },
  {
    id: 'workstation',
    title: 'WorkStation — Gestión de Equipos',
    description: 'Sistema fullstack para gestión de equipos de trabajo. Backend C# .NET con arquitectura limpia y frontend Vue.js.',
    longDescription: 'Plataforma colaborativa para gestión de proyectos y equipos. C# .NET con arquitectura limpia y Vue.js Composition API con documentación Swagger.',
    category: 'fullstack',
    status: 'academic',
    techs: [
      { name: 'Vue.js', color: 'green' },
      { name: 'C#', color: 'violet' },
      { name: '.NET', color: 'blue' },
      { name: 'SQL Server', color: 'teal' },
      { name: 'Swagger', color: 'green' },
    ],
    imagePlaceholder: 'WS',
    imageUrl: '/projects/WorkStation.png',
    githubUrl: 'https://github.com/WorkStation-MarronCoders/backeend',
    featured: true,
    year: 2024,
    highlights: [
      'Arquitectura limpia en C# .NET',
      'Vue.js Composition API',
      'Documentación completa con Swagger',
    ],
  },
  {
    id: 'video-chat-app',
    title: 'Video Chat App — WebRTC',
    description: 'Aplicación de videollamadas en tiempo real con TypeScript y WebRTC. Comunicación peer-to-peer sin servidor intermediario.',
    longDescription: 'Videochat con WebRTC para comunicación peer-to-peer directa. Señalización en tiempo real y manejo de streams de audio y video.',
    category: 'fullstack',
    status: 'open-source',
    techs: [
      { name: 'TypeScript', color: 'blue' },
      { name: 'WebRTC', color: 'cyan' },
      { name: 'WebSockets', color: 'violet' },
    ],
    imagePlaceholder: 'VC',
    imageUrl: '/projects/VideoChatApp.png',
    githubUrl: 'https://github.com/LuisDiazpe/video-chat-app',
    featured: false,
    year: 2025,
    highlights: [
      'Videollamadas peer-to-peer con WebRTC',
      'Señalización en tiempo real',
      'TypeScript strict end-to-end',
    ],
  },

  // Frontend
  {
    id: 'windows7-emulator',
    title: 'Windows 7 Online Emulator',
    description: 'Emulador de Windows 7 en el navegador con Visual Studio integrado. Angular puro, TypeScript, sin backend. Incluye emulador físico de Arduino.',
    longDescription: 'Emulador completo de Windows 7 que corre 100% en el navegador. Angular puro sin backend, Visual Studio integrado y conexión con emulador físico de Arduino.',
    category: 'frontend',
    status: 'production',
    techs: [
      { name: 'Angular', color: 'orange' },
      { name: 'TypeScript', color: 'blue' },
      { name: 'Arduino', color: 'teal' },
      { name: 'Web APIs', color: 'cyan' },
    ],
    imagePlaceholder: 'W7',
    imageUrl: '/projects/Windows7.png',
    githubUrl: 'https://github.com/LuisDiazpe/Windows7',
    liveUrl: 'https://windows7-rosy.vercel.app/?_vercel_share=iMmqwAIxQbhnS8dq5dmEtSj3Zj3bEbhw',
    featured: true,
    year: 2025,
    highlights: [
      'Emulador completo de Windows 7 en el browser',
      'Visual Studio integrado sin backend',
      'Angular puro con TypeScript strict',
      'Emulador físico de Arduino integrado',
    ],
  },
  {
    id: 'ecocrop-landing',
    title: 'EcoCrop — Landing Page',
    description: 'Landing page para aplicación agrícola EcoCrop, desarrollada por GreenSprout Innovations en la UPC. Diseño responsivo y animaciones CSS.',
    longDescription: 'Landing page profesional para la aplicación EcoCrop del equipo GreenSprout Innovations, desarrollada como proyecto universitario en la UPC. Foco en diseño responsivo, animaciones CSS y comunicación clara del producto.',
    category: 'frontend',
    status: 'academic',
    techs: [
      { name: 'HTML5', color: 'orange' },
      { name: 'CSS3', color: 'blue' },
      { name: 'JavaScript', color: 'orange' },
    ],
    imagePlaceholder: 'EC',
    imageUrl: '/projects/EcoCrop.png',
    liveUrl: 'https://greensprout-innovations.github.io/',
    featured: false,
    year: 2024,
    highlights: [
      'Diseño 100% responsivo',
      'Animaciones CSS puras',
      'Proyecto universitario UPC',
    ],
  },
  {
    id: 'cita-app',
    title: 'Cita — Ideas para Salidas',
    description: 'Página web de ideas y planificación de citas. Interfaz moderna con JavaScript vanilla.',
    longDescription: 'Aplicación web para generar y organizar ideas de citas. JavaScript vanilla, CSS avanzado y UX pensado.',
    category: 'frontend',
    status: 'personal',
    techs: [
      { name: 'JavaScript', color: 'orange' },
      { name: 'HTML5', color: 'orange' },
      { name: 'CSS3', color: 'blue' },
    ],
    imagePlaceholder: 'CI',
    imageUrl: '/projects/Cita.png',
    githubUrl: 'https://github.com/LuisDiazpe/Cita.github.io',
    liveUrl: 'https://luisdiazpe.github.io/Cita.github.io/',
    featured: false,
    year: 2025,
    highlights: [
      'JavaScript vanilla sin frameworks',
      'Diseño mobile-first',
    ],
  },
  {
    id: 'skilhub',
    title: 'SkilHub — Plataforma Educativa',
    description: 'Plataforma web educativa con interfaz moderna. CSS Grid, Flexbox y JavaScript vanilla puro.',
    longDescription: 'Interfaz educativa con diseño cuidado usando CSS Grid, Flexbox y JavaScript vanilla.',
    category: 'frontend',
    status: 'personal',
    techs: [
      { name: 'HTML5', color: 'orange' },
      { name: 'CSS3', color: 'blue' },
      { name: 'JavaScript', color: 'orange' },
    ],
    imagePlaceholder: 'SH',
    imageUrl: '/projects/Skillhub.png',
    liveUrl: 'https://luisdiazpe.github.io/Skilhub.github.io/',
    githubUrl: 'https://github.com/LuisDiazpe/Skilhub.github.io',
    featured: false,
    year: 2025,
    highlights: [
      'CSS Grid y Flexbox avanzado',
      'JavaScript vanilla sin frameworks',
    ],
  },

  //MOBILE
  {
    id: 'para-ti-flutter',
    title: 'Para Ti — App Flutter Personal',
    description: 'App móvil desarrollada en Flutter como regalo para su novia. Mensajes, sorpresas y contenido personalizado para cuando se sentía triste.',
    longDescription: 'Proyecto personal y significativo: una app Flutter hecha con amor, con contenido personalizado, mensajes especiales y sorpresas interactivas. Demuestra dominio de Flutter para experiencias de usuario emocionales y bien cuidadas.',
    category: 'mobile',
    status: 'personal',
    techs: [
      { name: 'Flutter', color: 'cyan' },
      { name: 'Dart', color: 'blue' },
    ],
    imagePlaceholder: 'PT',
    imageUrl: '/projects/ParaTiFlutter.png',
    featured: false,
    year: 2024,
    highlights: [
      'App completamente personalizada',
      'Animaciones y experiencia emocional cuidada',
      'Proyecto personal — Flutter puro',
    ],
  },
  {
    id: 'synera-kotlin',
    title: 'Synera Manager — App Kotlin (Gerentes)',
    description: 'App Android nativa en Kotlin para gerentes de empresa. Gestión de personal, anuncios corporativos, grupos de chat y control de actividades.',
    longDescription: 'Versión para gerentes de la plataforma Synera. App Android nativa con Kotlin, arquitectura MVVM, gestión de equipos, sistema de anuncios corporativos, grupos de chat en tiempo real y módulo de gestión de actividades y tareas.',
    category: 'mobile',
    status: 'academic',
    techs: [
      { name: 'Kotlin', color: 'violet' },
      { name: 'Android', color: 'green' },
      { name: 'MVVM', color: 'orange' },
      { name: 'REST APIs', color: 'blue' },
    ],
    imagePlaceholder: 'SM',
    imageUrl: '/projects/KotlinAPP.png',
    githubUrl: 'https://github.com/synera-app-moviles/centralis-kotlin',
    featured: true,
    year: 2024,
    highlights: [
      'App Android nativa con Kotlin',
      'Gestión de personal y actividades',
      'Anuncios corporativos y grupos de chat',
      'Arquitectura MVVM con Jetpack',
    ],
  },
  {
    id: 'synera-flutter',
    title: 'Synera Worker — App Flutter (Trabajadores)',
    description: 'App Flutter para trabajadores de empresa. Visualización de anuncios corporativos, acceso a salas de chat y gestión de actividades asignadas.',
    longDescription: 'Versión para trabajadores de la plataforma Synera. Construida en Flutter para compatibilidad multiplataforma. Los trabajadores pueden ver anuncios de la empresa, unirse a salas de chat y gestionar sus actividades diarias.',
    category: 'mobile',
    status: 'academic',
    techs: [
      { name: 'Flutter', color: 'cyan' },
      { name: 'Dart', color: 'blue' },
      { name: 'REST APIs', color: 'violet' },
    ],
    imagePlaceholder: 'SW',
    imageUrl: '/projects/FlutterAPP.png',
    githubUrl: 'https://github.com/synera-app-moviles/centralis_flutter',
    featured: false,
    year: 2024,
    highlights: [
      'App multiplataforma con Flutter',
      'Anuncios corporativos en tiempo real',
      'Salas de chat integradas',
      'Gestión de actividades asignadas',
    ],
  },

  //AUTOMATION
  {
    id: 'darkfunnels-automation',
    title: 'DarkFunnels.ai — Backend N8N',
    description: 'Backend completo en N8N para plataforma de marketing IA en WhatsApp. Voz automática, videos con IA y flujos de conversación inteligentes.',
    longDescription: 'Capa de automatización de DarkFunnels.ai: flujos N8N que gestionan conversaciones de WhatsApp, generan audio con voz IA, crean videos personalizados y manejan el ciclo de vida completo de cada lead.',
    category: 'automation',
    status: 'production',
    techs: [
      { name: 'N8N', color: 'orange' },
      { name: 'AI/LLMs', color: 'violet' },
      { name: 'WhatsApp API', color: 'green' },
      { name: 'Voice AI', color: 'cyan' },
      { name: 'Video AI', color: 'pink' },
    ],
    imagePlaceholder: 'DA',
    imageUrl: '/projects/DarkFunnels.png',
    liveUrl: 'https://darkfunnels.ai',
    featured: false,
    year: 2024,
    highlights: [
      'Flujos N8N para gestión completa de leads',
      'Integración de voz IA y video personalizado',
      'WhatsApp Business API en producción',
    ],
  },
  {
    id: 'meproind-automation',
    title: 'Meproind — Backend N8N Minero',
    description: 'Backend N8N para cálculo de costos mineros. Mesas gravimétricas, consumo eléctrico, agua y estimado de precios por mineral.',
    longDescription: 'Capa de automatización de Meproind: flujos N8N que exponen APIs de cálculo para el frontend React, procesando parámetros de operación minera y devolviendo estimados de costo en tiempo real.',
    category: 'automation',
    status: 'production',
    techs: [
      { name: 'N8N', color: 'orange' },
      { name: 'REST APIs', color: 'cyan' },
      { name: 'SQL', color: 'blue' },
      { name: 'Webhooks', color: 'violet' },
    ],
    imagePlaceholder: 'MA',
    imageUrl: '/projects/MeproindBack.png',
    featured: false,
    year: 2025,
    highlights: [
      'APIs de cálculo expuestas desde N8N',
      'Parámetros variables por operación',
      'Integración con base de datos SQL',
    ],
  },
  {
    id: 'n8n-scraping-ai',
    title: 'N8N — Scraping, IA & Llamadas',
    description: 'Colección de flujos N8N: scraping ético, automatizaciones con IA, llamadas automáticas y pipelines de datos multi-plataforma.',
    longDescription: 'Flujos de automatización N8N en producción: scraping de datos, automatizaciones con LLMs, llamadas de WhatsApp automáticas y pipelines ETL.',
    category: 'automation',
    status: 'personal',
    techs: [
      { name: 'N8N', color: 'orange' },
      { name: 'AI/LLMs', color: 'violet' },
      { name: 'Webhooks', color: 'cyan' },
      { name: 'REST APIs', color: 'blue' },
    ],
    imagePlaceholder: 'N8',
    imageUrl: '/projects/N8N.png',
    featured: true,
    year: 2024,
    highlights: [
      'Scraping ético y procesamiento de datos',
      'Automatizaciones con LLMs integrados',
      'Flujos de llamadas automáticas de WhatsApp',
      'Pipelines ETL multi-plataforma',
    ],
  },

  //backend
  {
    id: 'lexcoim-backend',
    title: 'Lexcoim.ai — Motor de Predicción',
    description: 'Backend en C# y Python para predicción de éxito de productos importados desde China a Perú. Análisis de mercado y estimado de rentabilidad.',
    longDescription: 'Motor backend de Lexcoim.ai construido con C# y Python. Procesa datos de mercado peruano, analiza productos candidatos a importar desde China y genera estimados de éxito y rentabilidad usando modelos de análisis.',
    category: 'backend',
    status: 'production',
    techs: [
      { name: 'C#', color: 'violet' },
      { name: 'Python', color: 'blue' },
      { name: 'APIs', color: 'cyan' },
      { name: '.NET', color: 'violet' },
    ],
    imagePlaceholder: 'LX',
    featured: false,
    year: 2024,
    highlights: [
      'Motor de análisis en C# y Python',
      'Predicción de éxito para importaciones',
      'Estimados de rentabilidad automatizados',
      'Plataforma en producción (actualmente inactiva)',
    ],
  },
  {
    id: 'secret-friend',
    title: 'Secret Friend — Amigo Secreto',
    description: 'App web para jugar al Amigo Secreto. Asignación aleatoria justa — sin duplicados ni autoasignación. Backend JavaScript puro.',
    longDescription: 'Proyecto backend para gestión de Amigo Secreto. Implementa algoritmo de asignación aleatoria garantizando que nadie se asigne a sí mismo y sin repetidos. Cada jugador ingresa su nombre y descubre a quién le tocó.',
    category: 'backend',
    status: 'open-source',
    techs: [
      { name: 'JavaScript', color: 'orange' },
      { name: 'HTML5', color: 'orange' },
      { name: 'CSS3', color: 'blue' },
    ],
    imagePlaceholder: 'SF',
    githubUrl: 'https://github.com/LuisDiazpe/secret-friend.github.io',
    liveUrl: 'https://luisdiazpe.github.io/secret-friend.github.io/',
    featured: false,
    year: 2024,
    highlights: [
      'Algoritmo de asignación justa sin duplicados',
      'Nadie se puede autoasignar',
      'Sin backend externo — lógica en el cliente',
    ],
  },
  {
    id: 'electrogest',
    title: 'ElectroGest — Gestión de Electrodomésticos',
    description: 'Software de gestión para negocios de venta de electrodomésticos. Algoritmos y estructuras de datos implementados en C++.',
    longDescription: 'Sistema de gestión de inventario con algoritmos de búsqueda y ordenamiento en C++ desde cero.',
    category: 'backend',
    status: 'open-source',
    techs: [
      { name: 'C++', color: 'blue' },
      { name: 'Estructuras de datos', color: 'violet' },
      { name: 'Algoritmos', color: 'teal' },
    ],
    imagePlaceholder: 'EG',
    githubUrl: 'https://github.com/LuisDiazpe/ElectroGest',
    featured: false,
    year: 2024,
    highlights: [
      'Algoritmos de búsqueda y ordenamiento propios',
      'Gestión de memoria manual en C++',
    ],
  },

  //IoT
  {
    id: 'smart-parking',
    title: 'Smart Parking Barrier',
    description: 'Sistema Arduino de control vehicular con sensores ultrasónicos, joystick, detección de gases MQ-135 y barrera automática con modo emergencia.',
    longDescription: 'Sistema embebido para control de acceso vehicular con detección de gases peligrosos, sensores ultrasónicos y barrera servo automática con modo emergencia.',
    category: 'iot',
    status: 'academic',
    techs: [
      { name: 'Arduino', color: 'teal' },
      { name: 'C++', color: 'blue' },
      { name: 'Sensores', color: 'green' },
      { name: 'IoT', color: 'orange' },
    ],
    imagePlaceholder: 'SP',
    imageUrl: '/projects/SmartParking.png',
    githubUrl: 'https://github.com/LuisDiazpe/Smart-Parking-Barrier-System-with-Gas-Emergency-Detection',
    featured: true,
    year: 2025,
    highlights: [
      'Detección de gases peligrosos MQ-135',
      'Control ultrasónico de acceso vehicular',
      'Modo de emergencia automático',
    ],
  },
  {
    id: '3d-console',
    title: '3D Console — Motor 3D en OLED',
    description: 'Consola con motor 3D implementado desde cero en C++. Juegos y animaciones 3D renderizadas en pantalla OLED sobre hardware embebido.',
    longDescription: 'Motor 3D implementado en C++ desde cero, optimizado para hardware embebido con pantalla OLED.',
    category: 'iot',
    status: 'personal',
    techs: [
      { name: 'C++', color: 'blue' },
      { name: 'OLED Display', color: 'teal' },
      { name: 'Render 3D', color: 'violet' },
    ],
    imagePlaceholder: '3D',
    imageUrl: '/projects/3DConsole.png',
    githubUrl: 'https://github.com/LuisDiazpe/3D-CONSOLE',
    featured: false,
    year: 2025,
    highlights: [
      'Motor 3D implementado desde cero en C++',
      'Renderizado en pantalla OLED',
      'Optimizado para hardware embebido',
    ],
  },
  {
    id: 'retro-console',
    title: 'RetroConsole — Consola Retro',
    description: 'Consola de juegos retro en C++. Juegos clásicos implementados desde cero sobre hardware embebido. MIT License.',
    longDescription: 'Videojuegos retro clásicos sobre hardware embebido en C++ puro sin librerías de game engine.',
    category: 'iot',
    status: 'open-source',
    techs: [
      { name: 'C++', color: 'blue' },
      { name: 'Hardware', color: 'green' },
      { name: 'Game Dev', color: 'violet' },
    ],
    imagePlaceholder: 'RC',
    imageUrl: '/projects/RetroConsole.png',
    githubUrl: 'https://github.com/LuisDiazpe/RetroConsole',
    featured: false,
    year: 2025,
    highlights: [
      'Juegos retro implementados desde cero',
      'Gráficos de bajo nivel en C++',
      'MIT License — open source',
    ],
  },
  {
    id: 'pastillero-ino',
    title: 'Pastillero Inteligente',
    description: 'Dispositivo IoT Arduino para recordatorios de medicamentos. Display LCD, buzzer y botones físicos.',
    longDescription: 'Sistema embebido con Arduino para recordatorios de medicamentos con display LCD y alertas sonoras.',
    category: 'iot',
    status: 'personal',
    techs: [
      { name: 'Arduino', color: 'teal' },
      { name: 'C++', color: 'blue' },
      { name: 'IoT', color: 'orange' },
    ],
    imagePlaceholder: 'PI',
    imageUrl: '/projects/Pastillero.png',
    githubUrl: 'https://github.com/LuisDiazpe/Pastillero.ino',
    featured: false,
    year: 2023,
    highlights: [
      'Display LCD y alertas sonoras',
      'Lógica de tiempo real en C++',
    ],
  },
  {
    id: 'game-cpp',
    title: 'GameC++ — Videojuego en C++',
    description: 'Videojuego implementado desde cero en C++. Motor propio con gráficos de consola y lógica de colisiones.',
    longDescription: 'Juego construido en C++ puro sin librerías de game engine. Motor de renderizado en consola, detección de colisiones y bucle de juego propio.',
    category: 'iot',
    status: 'personal',
    techs: [
      { name: 'C++', color: 'blue' },
      { name: 'Game Dev', color: 'violet' },
      { name: 'Algoritmos', color: 'teal' },
    ],
    imagePlaceholder: 'GC',
    githubUrl: 'https://github.com/LuisDiazpe/GameC-',
    featured: false,
    year: 2025,
    highlights: [
      'Motor de juego propio en C++',
      'Sin librerías externas de game engine',
    ],
  },

  //AI / PYTHON
  {
    id: 'assistant-pe',
    title: 'AssistantPe — Asistente IA Perú',
    description: 'Asistente virtual con contexto peruano. LLMs con Python para consultas y automatización local.',
    longDescription: 'Asistente IA en Python con contexto específico peruano. Integra modelos de lenguaje para responder consultas y automatizar tareas.',
    category: 'ai',
    status: 'personal',
    techs: [
      { name: 'Python', color: 'blue' },
      { name: 'LLMs', color: 'violet' },
      { name: 'NLP', color: 'cyan' },
    ],
    imagePlaceholder: 'AP',
    imageUrl: '/projects/AsistentePY.png',
    githubUrl: 'https://github.com/LuisDiazpe/AssistantPe',
    featured: true,
    year: 2025,
    highlights: [
      'Integración con modelos de lenguaje',
      'Contexto localizado para Perú',
    ],
  },
  {
    id: 'dibujo-python',
    title: 'DibujoPhyton — Arte Generativo',
    description: 'Generación de dibujos algorítmicos con Python. Arte generativo y visualizaciones matemáticas.',
    longDescription: 'Arte generativo con Python usando librerías de gráficos para patrones y visualizaciones matemáticas.',
    category: 'ai',
    status: 'personal',
    techs: [
      { name: 'Python', color: 'blue' },
      { name: 'Matplotlib', color: 'orange' },
      { name: 'Turtle', color: 'green' },
    ],
    imagePlaceholder: 'DP',
    imageUrl: '/projects/DibujoPY.png',
    githubUrl: 'https://github.com/LuisDiazpe/Dibujopiton',
    featured: false,
    year: 2025,
    highlights: [
      'Arte generativo con Python',
      'Patrones matemáticos visualizados',
    ],
  },
];