import type { Project } from '@/domain/project/Project';

export const PROJECTS_DATA: Project[] = [

  // FULLSTACK
  {
    id: 'arkabia-platform',
    title: 'Arkabia — Comercio Exterior SaaS',
    description: 'Plataforma SaaS peruana para importadores, exportadores y agentes de aduana. Gestión documental, trámites y flujos en tiempo real.',
    longDescription: 'Arkabia es una startup peruana de comercio exterior donde trabajo actualmente como Frontend Developer. Construí y mantuve múltiples módulos con React + TypeScript con arquitectura DDD.',
    category: 'fullstack',
    status: 'production',
    techs: [
      { name: 'React', color: 'cyan' },
      { name: 'TypeScript', color: 'blue' },
      { name: 'Tailwind CSS', color: 'teal' },
      { name: 'REST APIs', color: 'violet' },
    ],
    imagePlaceholder: 'AB',
    liveUrl: 'https://arkabia.com',
    featured: true,
    year: 2024,
    highlights: [
      'Plataforma en producción con usuarios reales',
      'Arquitectura de componentes escalable con DDD',
      'Integración con múltiples APIs de comercio exterior',
      'CI/CD con GitLab en equipo ágil',
    ],
  },
  {
    id: 'darkfunnels',
    title: 'DarkFunnels.ai — IA en WhatsApp',
    description: 'Plataforma de automatización de mensajes con IA en WhatsApp. Integración de voz, videos personalizados con IA y flujos N8N en producción.',
    longDescription: 'DarkFunnels.ai es una plataforma en producción para automatización de marketing en WhatsApp usando IA. Incluye voz automática, videos personalizados con IA y flujos N8N complejos.',
    category: 'automation',
    status: 'production',
    techs: [
      { name: 'N8N', color: 'orange' },
      { name: 'AI/LLMs', color: 'violet' },
      { name: 'WhatsApp API', color: 'green' },
      { name: 'Voice AI', color: 'cyan' },
      { name: 'Video AI', color: 'pink' },
    ],
    imagePlaceholder: 'DF',
    liveUrl: 'https://darkfunnels.ai',
    featured: true,
    year: 2024,
    highlights: [
      'Plataforma en producción con clientes reales',
      'Integración de voz IA para audios automáticos',
      'Videos personalizados generados con IA',
      'Flujos N8N complejos para gestión de conversaciones',
    ],
  },
  {
    id: 'meproind',
    title: 'Meproind — Costos Mineros con N8N',
    description: 'Backend completo en N8N para empresa minera. Calcula costos de mesas gravimétricas, flujo de agua, electricidad y precios por mineral.',
    longDescription: 'Actualmente en desarrollo para Meproind, empresa de servicios mineros. Backend construido completamente con N8N para cálculo de costos operativos mineros.',
    category: 'automation',
    status: 'production',
    techs: [
      { name: 'N8N', color: 'orange' },
      { name: 'REST APIs', color: 'cyan' },
      { name: 'SQL', color: 'blue' },
      { name: 'Webhooks', color: 'violet' },
    ],
    imagePlaceholder: 'MP',
    featured: true,
    year: 2025,
    highlights: [
      'Backend 100% construido con N8N',
      'Cálculo de costos de mesas gravimétricas',
      'Estimados de consumo eléctrico y agua',
      'Precios y costos por tipo de mineral',
    ],
  },
  {
    id: 'lexcoim',
    title: 'Lexcoim.ai — Predicción de Importación',
    description: 'Plataforma IA para predecir el éxito de productos importados desde China a Perú. Análisis de mercado y estimado de rentabilidad.',
    longDescription: 'Lexcoim.ai fue una plataforma en producción que usaba IA para analizar potencial de éxito de productos importados desde China al mercado peruano.',
    category: 'automation',
    status: 'production',
    techs: [
      { name: 'N8N', color: 'orange' },
      { name: 'AI/LLMs', color: 'violet' },
      { name: 'APIs', color: 'cyan' },
      { name: 'Python', color: 'blue' },
    ],
    imagePlaceholder: 'LX',
    featured: false,
    year: 2024,
    highlights: [
      'Análisis de mercado peruano con IA',
      'Predicción de éxito para importaciones desde China',
      'Estimados de rentabilidad automatizados',
      'Plataforma en producción (actualmente inactiva)',
    ],
  },
  {
    id: 'spliteasy-fullstack',
    title: 'SplitEasy — Gastos Compartidos',
    description: 'App fullstack para gestión de gastos entre grupos. Angular + Java Spring Boot con arquitectura DDD completa.',
    longDescription: 'Proyecto académico fullstack con Domain Driven Design en Spring Boot y frontend Angular con autenticación JWT.',
    category: 'fullstack',
    status: 'academic',
    techs: [
      { name: 'Angular', color: 'orange' },
      { name: 'Java', color: 'orange' },
      { name: 'Spring Boot', color: 'green' },
      { name: 'MySQL', color: 'blue' },
      { name: 'DDD', color: 'violet' },
    ],
    imagePlaceholder: 'SE',
    githubUrl: 'https://github.com/1ASI0729-2510-4313-G3-SplitEasy/backend-app',
    featured: false,
    year: 2024,
    highlights: [
      'Arquitectura DDD en backend Java',
      'API RESTful con Spring Boot y JWT',
      'Frontend Angular con gestión reactiva de estado',
    ],
  },
  {
    id: 'workstation',
    title: 'WorkStation — Gestión de Equipos',
    description: 'Sistema fullstack para gestión de equipos. Backend C# .NET arquitectura limpia y frontend Vue.js.',
    longDescription: 'Plataforma colaborativa para gestión de proyectos y equipos. C# .NET con arquitectura limpia y Vue.js Composition API.',
    category: 'fullstack',
    status: 'academic',
    techs: [
      { name: 'Vue.js', color: 'green' },
      { name: 'C#', color: 'violet' },
      { name: '.NET', color: 'blue' },
      { name: 'SQL Server', color: 'teal' },
    ],
    imagePlaceholder: 'WS',
    githubUrl: 'https://github.com/WorkStation-MarronCoders/backeend',
    featured: false,
    year: 2024,
    highlights: [
      'Arquitectura limpia en C# .NET',
      'Vue.js Composition API',
      'Documentación completa con Swagger',
    ],
  },
  {
    id: 'video-chat-app',
    title: 'Video Chat App — WebRTC',
    description: 'Aplicación de videollamadas en tiempo real con TypeScript y WebRTC. Comunicación peer-to-peer sin servidor intermediario.',
    longDescription: 'Videochat con WebRTC para comunicación peer-to-peer directa. Señalización en tiempo real y manejo de streams de audio y video.',
    category: 'fullstack',
    status: 'open-source',
    techs: [
      { name: 'TypeScript', color: 'blue' },
      { name: 'WebRTC', color: 'cyan' },
      { name: 'WebSockets', color: 'violet' },
    ],
    imagePlaceholder: 'VC',
    githubUrl: 'https://github.com/LuisDiazpe/video-chat-app',
    featured: false,
    year: 2025,
    highlights: [
      'Videollamadas peer-to-peer con WebRTC',
      'Señalización en tiempo real',
      'TypeScript strict end-to-end',
    ],
  },

  // FRONTEND
  {
    id: 'windows7-emulator',
    title: 'Windows 7 Online Emulator',
    description: 'Emulador de Windows 7 en el navegador con Visual Studio integrado. Angular puro, TypeScript, sin backend. Incluye emulador físico de Arduino.',
    longDescription: 'Emulador completo de Windows 7 que corre 100% en el navegador. Angular puro sin backend, Visual Studio integrado y conexión con emulador físico de Arduino.',
    category: 'frontend',
    status: 'personal',
    techs: [
      { name: 'Angular', color: 'orange' },
      { name: 'TypeScript', color: 'blue' },
      { name: 'Arduino', color: 'teal' },
      { name: 'Web APIs', color: 'cyan' },
    ],
    imagePlaceholder: 'W7',
    githubUrl: 'https://github.com/LuisDiazpe/Windows7',
    featured: true,
    year: 2025,
    highlights: [
      'Emulador completo de Windows 7 en el browser',
      'Visual Studio integrado sin backend',
      'Angular puro con TypeScript strict',
      'Emulador físico de Arduino integrado',
    ],
  },
  {
    id: 'cita-app',
    title: 'Cita — Ideas para Salidas',
    description: 'Página web de ideas y planificación de citas. Interfaz moderna con JavaScript vanilla.',
    longDescription: 'Aplicación web para generar y organizar ideas de citas. JavaScript vanilla, CSS avanzado y UX pensado.',
    category: 'frontend',
    status: 'personal',
    techs: [
      { name: 'JavaScript', color: 'orange' },
      { name: 'HTML5', color: 'orange' },
      { name: 'CSS3', color: 'blue' },
    ],
    imagePlaceholder: 'CI',
    githubUrl: 'https://github.com/LuisDiazpe/Cita.github.io',
    liveUrl: 'https://luisdiazpe.github.io/Cita.github.io/',
    featured: false,
    year: 2025,
    highlights: [
      'JavaScript vanilla sin frameworks',
      'Diseño mobile-first',
    ],
  },
  {
    id: 'skilhub',
    title: 'SkilHub — Plataforma Educativa',
    description: 'Plataforma web educativa con interfaz moderna. CSS Grid, Flexbox y JavaScript vanilla puro.',
    longDescription: 'Interfaz educativa con diseño cuidado usando CSS Grid, Flexbox y JavaScript vanilla.',
    category: 'frontend',
    status: 'personal',
    techs: [
      { name: 'HTML5', color: 'orange' },
      { name: 'CSS3', color: 'blue' },
      { name: 'JavaScript', color: 'orange' },
    ],
    imagePlaceholder: 'SH',
    liveUrl: 'https://luisdiazpe.github.io/Skilhub.github.io/',
    githubUrl: 'https://github.com/LuisDiazpe/Skilhub.github.io',
    featured: false,
    year: 2025,
    highlights: [
      'CSS Grid y Flexbox avanzado',
      'JavaScript vanilla sin frameworks',
    ],
  },

  //AUTOMATION
  {
    id: 'n8n-scraping-ai',
    title: 'N8N — Scraping, IA & Llamadas',
    description: 'Flujos N8N: scraping ético, automatizaciones con IA, llamadas automáticas y pipelines de datos multi-plataforma.',
    longDescription: 'Colección de flujos de automatización N8N en producción: scraping de datos, automatizaciones con modelos de IA, llamadas de WhatsApp automáticas y pipelines ETL.',
    category: 'automation',
    status: 'personal',
    techs: [
      { name: 'N8N', color: 'orange' },
      { name: 'AI/LLMs', color: 'violet' },
      { name: 'Webhooks', color: 'cyan' },
      { name: 'REST APIs', color: 'blue' },
    ],
    imagePlaceholder: 'N8',
    featured: true,
    year: 2024,
    highlights: [
      'Scraping ético y procesamiento de datos',
      'Automatizaciones con LLMs integrados',
      'Flujos de llamadas automáticas',
      'Pipelines ETL multi-plataforma',
    ],
  },

  //IOT
  {
    id: 'smart-parking',
    title: 'Smart Parking Barrier — Control Vehicular',
    description: 'Sistema inteligente Arduino: sensores ultrasónicos, joystick, detección de gases MQ-135 y barrera automática con modo emergencia.',
    longDescription: 'Sistema embebido para control de acceso vehicular con detección de gases peligrosos, sensores ultrasónicos y barrera servo automática.',
    category: 'iot',
    status: 'academic',
    techs: [
      { name: 'Arduino', color: 'teal' },
      { name: 'C++', color: 'blue' },
      { name: 'Sensores', color: 'green' },
      { name: 'IoT', color: 'orange' },
    ],
    imagePlaceholder: 'SP',
    githubUrl: 'https://github.com/LuisDiazpe/Smart-Parking-Barrier-System-with-Gas-Emergency-Detection',
    featured: true,
    year: 2025,
    highlights: [
      'Detección de gases peligrosos MQ-135',
      'Control ultrasónico de acceso vehicular',
      'Modo de emergencia automático',
    ],
  },
  {
    id: '3d-console',
    title: '3D Console — Animaciones en OLED',
    description: 'Consola con motor 3D desde cero en C++. Juegos y animaciones 3D renderizadas en pantalla OLED sobre hardware embebido.',
    longDescription: 'Motor 3D implementado en C++ desde cero, optimizado para hardware embebido con pantalla OLED pequeña.',
    category: 'iot',
    status: 'personal',
    techs: [
      { name: 'C++', color: 'blue' },
      { name: 'OLED Display', color: 'teal' },
      { name: 'Render 3D', color: 'violet' },
    ],
    imagePlaceholder: '3D',
    githubUrl: 'https://github.com/LuisDiazpe/3D-CONSOLE',
    featured: true,
    year: 2025,
    highlights: [
      'Motor 3D implementado desde cero en C++',
      'Renderizado en pantalla OLED',
      'Optimizado para hardware embebido',
    ],
  },
  {
    id: 'retro-console',
    title: 'RetroConsole — Consola Retro',
    description: 'Consola de juegos retro en C++. Juegos clásicos implementados desde cero sobre hardware embebido. MIT License.',
    longDescription: 'Videojuegos retro clásicos sobre hardware embebido en C++ puro sin librerías de game engine.',
    category: 'iot',
    status: 'open-source',
    techs: [
      { name: 'C++', color: 'blue' },
      { name: 'Hardware', color: 'green' },
      { name: 'Game Dev', color: 'violet' },
    ],
    imagePlaceholder: 'RC',
    githubUrl: 'https://github.com/LuisDiazpe/RetroConsole',
    featured: false,
    year: 2025,
    highlights: [
      'Juegos retro implementados desde cero',
      'Gráficos de bajo nivel en C++',
      'MIT License — open source',
    ],
  },
  {
    id: 'pastillero-ino',
    title: 'Pastillero Inteligente',
    description: 'Dispositivo IoT Arduino para recordatorios de medicamentos. Display LCD, buzzer y botones físicos.',
    longDescription: 'Sistema embebido con Arduino para recordatorios de medicamentos con display LCD y alertas sonoras.',
    category: 'iot',
    status: 'personal',
    techs: [
      { name: 'Arduino', color: 'teal' },
      { name: 'C++', color: 'blue' },
      { name: 'IoT', color: 'orange' },
    ],
    imagePlaceholder: 'PI',
    githubUrl: 'https://github.com/LuisDiazpe/Pastillero.ino',
    featured: false,
    year: 2023,
    highlights: [
      'Display LCD y alertas sonoras',
      'Lógica de tiempo real en C++',
    ],
  },

  // AI / PYTHON
  {
    id: 'assistant-pe',
    title: 'AssistantPe — Asistente IA Perú',
    description: 'Asistente virtual con contexto peruano. LLMs con Python para consultas y automatización local.',
    longDescription: 'Asistente IA en Python con contexto específico peruano. Integra modelos de lenguaje para responder consultas y automatizar tareas.',
    category: 'ai',
    status: 'personal',
    techs: [
      { name: 'Python', color: 'blue' },
      { name: 'LLMs', color: 'violet' },
      { name: 'NLP', color: 'cyan' },
    ],
    imagePlaceholder: 'AP',
    githubUrl: 'https://github.com/LuisDiazpe/AssistantPe',
    featured: false,
    year: 2025,
    highlights: [
      'Integración con modelos de lenguaje',
      'Contexto localizado para Perú',
    ],
  },
  {
    id: 'dibujo-python',
    title: 'DibujoPhyton — Arte Generativo',
    description: 'Generación de dibujos algorítmicos con Python. Arte generativo y visualizaciones matemáticas.',
    longDescription: 'Arte generativo con Python usando librerías de gráficos para patrones y visualizaciones matemáticas.',
    category: 'ai',
    status: 'personal',
    techs: [
      { name: 'Python', color: 'blue' },
      { name: 'Matplotlib', color: 'orange' },
      { name: 'Turtle', color: 'green' },
    ],
    imagePlaceholder: 'DP',
    githubUrl: 'https://github.com/LuisDiazpe/Dibujopiton',
    featured: false,
    year: 2025,
    highlights: [
      'Arte generativo con Python',
      'Patrones matemáticos visualizados',
    ],
  },

  //BACKEND
  {
    id: 'electrogest',
    title: 'ElectroGest — Gestión de Electrodomésticos',
    description: 'Software de gestión para negocios de venta de electrodomésticos. Algoritmos y estructuras de datos en C++.',
    longDescription: 'Sistema de gestión de inventario con algoritmos de búsqueda y ordenamiento en C++.',
    category: 'backend',
    status: 'open-source',
    techs: [
      { name: 'C++', color: 'blue' },
      { name: 'Estructuras de datos', color: 'violet' },
      { name: 'Algoritmos', color: 'teal' },
    ],
    imagePlaceholder: 'EG',
    githubUrl: 'https://github.com/LuisDiazpe/ElectroGest',
    featured: false,
    year: 2024,
    highlights: [
      'Algoritmos de búsqueda y ordenamiento propios',
      'Gestión de memoria manual en C++',
    ],
  },
];